### PR TITLE
Create Call Rest is missing target headers on outdial

### PR DESCRIPTION
**Pull request by ajukes**
When adding customer headers to the target object on a rest dial, the headers are now present on rest dial.

### CODE REVIEW

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
can you rebase @ajukes

**Comment by ajukes** [comment]
rebased @davehorton

**Comment by davehorton** [comment]
hmm still showing out of date..

**Comment by ajukes** [comment]
How about now?

**Review by davehorton — APPROVED** [review]

**Pull request merged**
