### PR TITLE
fix recognizer/synthesizer label wrongly select between verb and app

### PR DESCRIPTION
**Pull request by xquanluu**
continue to fix PR:

https://github.com/jambonz/jambonz-feature-server/pull/829

### CODE REVIEW

**Comment by vdharashive** [comment]
@xquanluu did you manage to look into when google asr is used as primary , its not falling back to secondary

**Comment by xquanluu** [comment]
ah I forgot that. checking that now

**Comment by xquanluu** [comment]
Fixed ASR cannot fallback if feature server cannot find stt credential

**Comment by vdharashive** [comment]
@xquanluu there is on issue found for tts , if primary fails or fallback fails it's not invoking jambonz error event to bot

**Comment by vdharashive** [comment]
@xquanluu @davehorton i have got this tested and its working fine you can merge this

**Review by davehorton — APPROVED** [review]

**Pull request merged**
