### PR TITLE
fix asr error notify wrong vendor name

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by davehorton** [comment]
is this ready for merge?

**Comment by vdharashive** [comment]
@davehorton and @xquanluu please merge this in 0.9 release its working as expected

**Comment by davehorton** [comment]
I am waiting until @xquanluu moves this from draft status

**Comment by vdharashive** [comment]
@davehorton can you merge this in 0.9 i have tested it

**Pull request merged**
