### PR TITLE
feat: rest:dial amd

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Review by davehorton — COMMENTED** [review]
Is it going to be possible to add a test case for this?

**Review by davehorton — COMMENTED** [review]
Is it going to be possible to add a test case for this?

**Comment by xquanluu** [comment]
Yes, I'm adding the testcase, I'm first check if my changes break legacy testsuite.

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
seems like test is failing
```
# test create-call amd
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot destructure property 'vendor' of 'ep.amd' as it is null.
```

**Pull request merged**
