### PR TITLE
fix conference in feature server cluster join, leave, end events are …

### PR DESCRIPTION
**Pull request by xquanluu**
…missing original data

#799

### CODE REVIEW

**Comment by xquanluu** [comment]
Hi @davehorton 

tested in jambonz.xyz cluster,

conference in cluster is working and conference status hook is sent with correct data for both participants in a call.

**Comment by davehorton** [comment]
ok please rebase and I will merge

**Comment by xquanluu** [comment]
Hi @davehorton I rebased.

**Comment by vdharashive** [comment]
@davehorton can you please merge this pr

**Review by davehorton — APPROVED** [review]

**Pull request merged**
