### PR TITLE
wip

### PR DESCRIPTION
**Pull request by davehorton**

### CODE REVIEW

**Comment by vdharashive** [comment]
@davehorton can we merge say file issue logging like , file not found , not reachable etc,  into main branch that will help to track any issue

**Comment by davehorton** [comment]
> @davehorton can we merge say file issue logging like , file not found , not reachable etc, into main branch that will help to track any issue

I'm confused about this comment as this PR has nothing to do with that I dont' think.  I am awaiting the results of your testing on this PR

**Comment by vdharashive** [comment]
@davehorton we are facing kill prompt issues after even fixing the freeswitch cache issue , will be testing this PR

**Comment by vdharashive** [comment]
@davehorton can this be rebased since i need to test this in production , and capture the logs , i tried but there are conflicts

**Comment by vdharashive** [comment]
@davehorton 150 calls tested no issue reported we can merge this

**Comment by vdharashive** [comment]
@davehorton can you please merge this

**Comment by vdharashive** [comment]
@davehorton can you please merge this , its live in production for 3 weeks now , issue issues found

**Pull request merged**
