### PR TITLE
support elevenlabs options

### PR DESCRIPTION
**Pull request by xquanluu**
https://github.com/jambonz/jambonz-feature-server/issues/541

### CODE REVIEW

**Comment by Catharsis68** [comment]
We'd have the need to pass these options via `Config verb` - similar to e.g `deepgramOptions` but within the `synthesizer` property.  Or we could use the existing  `[synthesizer.options](https://github.com/jambonz/verb-specifications/blob/f860074a244373efeabc177e92273ce874b71867/specs.json#L494C12-L494C13)` property

**Comment by xquanluu** [comment]
Thanks @Catharsis68 for the review, I have updated the code to get the options from synthezier.options.

this is deployed in jambonz.me

**Comment by paulotelles** [comment]
@xquanluu 

The main goal here is to have the option to change those configs during the call like
`

{
      "config":{
        "synthesizer":{
          "vendor":"microsoft",
          "language":"en-US",
          "voice":"en-US-AriaNeural"
         "options": {
             "stability": 0.5,
             "similarity_boost": 0.5
             "model": turbo_v2
             "style": 1
             "use_speaker_boost": "true"
        }
}
`

**Comment by xquanluu** [comment]
Hi @paulotelles the options is not being used for only elevenlabs, and for me it should be generic enough that later if there is something change at elevenlabs we don't need to come here and fix the format of options again. the application just very simple update the options to follow the new rule

Currently, You have to provide elevenlabs configuration to options. please rethink.

**Review by davehorton — APPROVED** [review]

**Pull request merged**
