### PR TITLE
Allow Say, Gather, Transcribe is able to finished if there is error for speech credential

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by vdharashive** [comment]
@xquanluu we have tested and the fix is working

**Comment by vdharashive** [comment]
@xquanluu @davehorton this can be merged

**Comment by davehorton** [comment]
@xquanluu please change to review if you feel it is ready for merge

**Comment by xquanluu** [comment]
Please help to review this @davehorton, I have marked it as ready

**Review by davehorton — APPROVED** [review]

**Pull request merged**
