### PR TITLE
update getAwsAuthToken use parameters in an object

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by vdharashive** [comment]
@xquanluu can you remove printing of keys and secret in log file

**Comment by vdharashive** [comment]
{"level":20,"time":1718376639790,"pid":1849456,"hostname":"ip-10-0-1-227","results":{"secretAccessKey":........=="},"msg":"retrieveHash for key aws:......"}

**Comment by xquanluu** [comment]
Hi @vdharashive I cannot find where the log is printed by key **retrieveHash for**, could you grep on your source to see if it's added by your team?

**Comment by xquanluu** [comment]
Hi @vdharashive can you also please run test on API server for getting TTS from REST API as well.

**Review by davehorton — APPROVED** [review]

**Pull request merged**
