### PR TITLE
clear gather timeout if imterim result received

### PR DESCRIPTION
**Pull request by xquanluu**
#777

### CODE REVIEW

**Comment by davehorton** [comment]
I have a concern with this change.  If we ever receive an interim transcript and then never get a final transcript, we will wait forever.  I believe I have seen this happen with google.  So I don't think I can merge this PR until it has been tested pretty extensively with google STT

**Comment by xquanluu** [comment]
Hi @davehorton @vdharashive 

I agreed with Dave that gather timeout is a must and should not be clear to make sure gather will not be a deadlock. there are 2 options:
1/ reset gather timeout after interim transcript
2/ the application set higher value for gather timeout.

I would love to go with option 2 instead of this PR or option 1

**Comment by vdharashive** [comment]
@xquanluu @davehorton we have tested this with google,deepgram and Microsoft no issues found , also i have made this live in production , client has mentioned the issue has been resolved. its safe to move to Merge this PR

**Comment by vdharashive** [comment]
@xquanluu we can go with option  1/ reset gather timeout after interim transcript

**Comment by davehorton** [comment]
> @xquanluu we can go with option 1/ reset gather timeout after interim transcript

I agree

**Comment by vdharashive** [comment]
@xquanluu see if this can be completed as agreed

**Comment by davehorton** [comment]
will merge after https://github.com/jambonz/jambonz-feature-server/pull/842

**Review by davehorton — APPROVED** [review]

**Pull request merged**
